# Counting inversions in an array

Merge_Sort_Count will be the main backbone of the code

### Input 

In [1]:
import numpy as np

In [2]:
!ls

Homework1_Coding.ipynb input.txt              programming_hw1.png


In [43]:
df = np.loadtxt('input.txt')
alist = [54,26,93,17,77,31,44,55,20]

In [12]:
df.shape # (100000, )

(100000,)

In [14]:
type(df) # np.ndarray 

numpy.ndarray

In [16]:
len(df)//2

50000

In [3]:
df

array([ 54044.,  14108.,  79294., ...,  74018.,  71187.,  91901.])

In [20]:
len(df[:50000])

50000

In [21]:
len(df[50000:])

50000

TypeError: object of type 'numpy.float64' has no len()

### Merge Sort

In [36]:
##############################################################
# ------------ Task 1: Merge Sort Algorithm -----------------#
##############################################################
# To make sure memory is constant in time


def merge_sort(in_array):
    '''
    Input: An array of integers
    Output: Sorted array of integers
    Description: 
    The following algorithm implements the merge sort algorithm as a divide and conquer 
    algo
    '''
    print("Splitting ",in_array)
    # Base Case
    if len(in_array) == 1:
        print('Hitting Base Case')
        return(in_array)
    # Main Code
    elif len(in_array) > 1:
        # ----- Merge Sort Implementation -------#
        # Determine the midpoint
        mid = len(in_array)//2 
        left_array = in_array[:mid]
        right_array = in_array[mid:]
        print('Starting to sort left')
        left_sorted = merge_sort(left_array)
        print('Starting to sort right' )
        right_sorted = merge_sort(right_array)
        
        # Invoking the helper function
        #sorted_array = merge(left_sorted, right_sorted)
        #merge(left_sorted, right_sorted)
        # return sorted array
        #return(sorted_array)
    
        # parameters
        i = 0 # Counter for elements in the left array
        j = 0 # Counter for elements in the right array
        k = 0 # Counter for the sorted array
        #size = len(left_sorted) + len(right_sorted)
        #sorted_array = np.empty(size, dtype = int) # Initializing the sorted array
        print('Merging', left_sorted, ' and ', right_sorted )
        # Case 1
        while((i < len(left_sorted)) and j < len(right_sorted)):
            if(left_sorted[i] <= right_sorted[j]):
                in_array[k] = left_sorted[i]
                i = i + 1
                k = k + 1
            else:
                in_array[k] = right_sorted[j]
                j = j + 1
                k = k + 1
            
        # Case 2
        while(i < len(left_sorted)):
            in_array[k] = left_sorted[i]
            i = i + 1
            k = k + 1
        
        # Case 3
        while(j < len(right_sorted)):
            in_array[k] = right_sorted[j]
            j = j + 1
            k = k + 1
        return(in_array)
    else: 
        #print('Error')
        return


    

In [9]:
def merge(left, right):
    '''
    Input: 2 sorted arrays of integers
    Output: A single Sorted array of integers
    Description: 
    The following function implements a helper function
    for the merge sort algorithm as a divide and conquer 
    algo
    '''
    # parameters
    i = 0 # Counter for elements in the left array
    j = 0 # Counter for elements in the right array
    k = 0 # Counter for the sorted array
    size = len(left) + len(right)
    sorted_array = np.empty(size, dtype = int) # Initializing the sorted array
    
    # Case 1
    while((i < len(left)) and j < len(right)):
        if(left[i] <= right[j]):
            sorted_array[k] = left[i]
            i = i + 1
            k = k + 1
        else:
            sorted_array[k] = right[j]
            j = j + 1
            k = k + 1
            
    # Case 2
    while(i < len(left)):
        sorted_array[k] = left[i]
        i = i + 1
        k = k + 1
        
    # Case 3
    while(j < len(right)):
        sorted_array[k] = right[j]
        j = j + 1
        k = k + 1
    
    # return sorted array
    #return(sorted_array)

In [44]:
tmp2 = merge_sort(alist)
tmp2

Splitting  [54, 26, 93, 17, 77, 31, 44, 55, 20]
Starting to sort left
Splitting  [54, 26, 93, 17]
Starting to sort left
Splitting  [54, 26]
Starting to sort left
Splitting  [54]
Hitting Base Case
Starting to sort right
Splitting  [26]
Hitting Base Case
Merging [54]  and  [26]
Starting to sort right
Splitting  [93, 17]
Starting to sort left
Splitting  [93]
Hitting Base Case
Starting to sort right
Splitting  [17]
Hitting Base Case
Merging [93]  and  [17]
Merging [26, 54]  and  [17, 93]
Starting to sort right
Splitting  [77, 31, 44, 55, 20]
Starting to sort left
Splitting  [77, 31]
Starting to sort left
Splitting  [77]
Hitting Base Case
Starting to sort right
Splitting  [31]
Hitting Base Case
Merging [77]  and  [31]
Starting to sort right
Splitting  [44, 55, 20]
Starting to sort left
Splitting  [44]
Hitting Base Case
Starting to sort right
Splitting  [55, 20]
Starting to sort left
Splitting  [55]
Hitting Base Case
Starting to sort right
Splitting  [20]
Hitting Base Case
Merging [55]  and 

[17, 20, 26, 31, 44, 54, 55, 77, 93]

In [46]:
df[:100]

array([  2995.,   2995.,   2995.,   2995.,   2995.,   2995.,   2995.,
         9083.,   9083.,   9083.,  16122.,  90436.,   4615.,  40660.,
        25675.,  58943.,  92904.,   9900.,  95588.,  46120.,  29390.,
        91323.,  85363.,  45738.,  80717.,  57415.,   7637.,   8540.,
         6336.,  45434.,  65895.,  61811.,   8959.,   9139.,  31027.,
        87662.,   2484.,  65550.,  23260.,  15616.,   3490.,  49568.,
         5979.,  44737.,  52808.,  72122.,  37957.,  34826.,  21419.,
        73531.,  94323.,  52910.,  84496.,  71799.,  50162.,   1692.,
         1565.,  59279.,  56864.,  20141.,  13893.,  63942.,   6055.,
        33424.,  44771.,  25678.,  33639.,  27793.,  41268.,   1857.,
        63388.,  32976.,  46195.,  61291.,  61740.,  61680.,  45264.,
        76361.,  49243.,  73250.,  67432.,  29124.,  15198.,  30626.,
        18950.,  13857.,  32569.,  45179.,  47696.,  21283.,  77169.,
        26357.,  97885.,  54741.,  57246.,  61929.,  25997.,  45859.,
         3353.,  322

In [45]:
tmp = merge_sort(df[:10])
tmp

Splitting  [ 54044.  14108.  79294.  29649.  25260.  60660.   2995.  53777.  49689.
   9083.]
Starting to sort left
Splitting  [ 54044.  14108.  79294.  29649.  25260.]
Starting to sort left
Splitting  [ 54044.  14108.]
Starting to sort left
Splitting  [ 54044.]
Hitting Base Case
Starting to sort right
Splitting  [ 14108.]
Hitting Base Case
Merging [ 54044.]  and  [ 14108.]
Starting to sort right
Splitting  [ 79294.  29649.  25260.]
Starting to sort left
Splitting  [ 79294.]
Hitting Base Case
Starting to sort right
Splitting  [ 29649.  25260.]
Starting to sort left
Splitting  [ 29649.]
Hitting Base Case
Starting to sort right
Splitting  [ 25260.]
Hitting Base Case
Merging [ 29649.]  and  [ 25260.]
Merging [ 79294.]  and  [ 25260.  25260.]
Merging [ 14108.  14108.]  and  [ 25260.  25260.  25260.]
Starting to sort right
Splitting  [ 60660.   2995.  53777.  49689.   9083.]
Starting to sort left
Splitting  [ 60660.   2995.]
Starting to sort left
Splitting  [ 60660.]
Hitting Base Case
Start

array([ 2995.,  2995.,  2995.,  2995.,  2995.,  2995.,  2995.,  9083.,
        9083.,  9083.])

In [3]:
15//2

7

In [30]:
tmp = np.empty(2, dtype = int)

In [27]:
np.array?

SyntaxError: invalid syntax (<ipython-input-33-282a4d518e1b>, line 2)

In [11]:
def mergeSort(alist):
    print("Splitting ",alist)
    if len(alist) == 1:
        return
    elif len(alist)>1:
        mid = len(alist)//2
        lefthalf = alist[:mid]
        righthalf = alist[mid:]

        mergeSort(lefthalf)
        mergeSort(righthalf)

        i=0
        j=0
        k=0
        while i < len(lefthalf) and j < len(righthalf):
            if lefthalf[i] < righthalf[j]:
                alist[k]=lefthalf[i]
                i=i+1
            else:
                alist[k]=righthalf[j]
                j=j+1
            k=k+1

        while i < len(lefthalf):
            alist[k]=lefthalf[i]
            i=i+1
            k=k+1

        while j < len(righthalf):
            alist[k]=righthalf[j]
            j=j+1
            k=k+1
    print("Merging ",alist)

alist = [54,26,93,17,77,31,44,55,20]
mergeSort(alist)
print(alist)


Splitting  [54, 26, 93, 17, 77, 31, 44, 55, 20]
Splitting  [54, 26, 93, 17]
Splitting  [54, 26]
Splitting  [54]
Splitting  [26]
Merging  [26, 54]
Splitting  [93, 17]
Splitting  [93]
Splitting  [17]
Merging  [17, 93]
Merging  [17, 26, 54, 93]
Splitting  [77, 31, 44, 55, 20]
Splitting  [77, 31]
Splitting  [77]
Splitting  [31]
Merging  [31, 77]
Splitting  [44, 55, 20]
Splitting  [44]
Splitting  [55, 20]
Splitting  [55]
Splitting  [20]
Merging  [20, 55]
Merging  [20, 44, 55]
Merging  [20, 31, 44, 55, 77]
Merging  [17, 20, 26, 31, 44, 54, 55, 77, 93]
[17, 20, 26, 31, 44, 54, 55, 77, 93]


In [5]:
mergeSort(df[:100])

Splitting  [ 54044.  14108.  79294.  29649.  25260.  60660.   2995.  53777.  49689.
   9083.  16122.  90436.   4615.  40660.  25675.  58943.  92904.   9900.
  95588.  46120.  29390.  91323.  85363.  45738.  80717.  57415.   7637.
   8540.   6336.  45434.  65895.  61811.   8959.   9139.  31027.  87662.
   2484.  65550.  23260.  15616.   3490.  49568.   5979.  44737.  52808.
  72122.  37957.  34826.  21419.  73531.  94323.  52910.  84496.  71799.
  50162.   1692.   1565.  59279.  56864.  20141.  13893.  63942.   6055.
  33424.  44771.  25678.  33639.  27793.  41268.   1857.  63388.  32976.
  46195.  61291.  61740.  61680.  45264.  76361.  49243.  73250.  67432.
  29124.  15198.  30626.  18950.  13857.  32569.  45179.  47696.  21283.
  77169.  26357.  97885.  54741.  57246.  61929.  25997.  45859.   3353.
  32204.]
Splitting  [ 54044.  14108.  79294.  29649.  25260.  60660.   2995.  53777.  49689.
   9083.  16122.  90436.   4615.  40660.  25675.  58943.  92904.   9900.
  95588.  46120.  2

In [10]:
merge_sort(df[:100])

Splitting  [  1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.   1565.
   1565.   1565.   1565.   1857.   1857.   1857.   1857.   1857.   1857.
   1857.   1857.   1857.   1857.   1857.   1857.   1857.   3353.   3353.
   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.
   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.
   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.   3353.
  32204.]
Splitting  [ 1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.
  1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.  1565.
  1565.  1565.  1565.  

TypeError: object of type 'NoneType' has no len()